language: haskell
ghc: 7.8
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install coq -qq
  - "cd src/extracted"
install:
  - "cabal install --only-dependencies --enable-tests --reorder-goals"
script:
  - "cabal configure --enable-tests && cabal build && cabal test"
