language: haskell
ghc: 7.8
before_install:
  - opam repo add coq-released https://coq.inria.fr/opam/released
  - opam install coq.8.4.5
  - "cd ../src/extracted"
install:
  - "cabal install --only-dependencies --enable-tests --reorder-goals"
script:
  - "cabal configure --enable-tests && cabal build && cabal test"
